config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about"
  get 'search' => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower'
    get 'followers' => 'relationships#followed'
  end

  resources :chats, only: [:show, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = BookComment.new(book_comment_params)
    @comment.user_id = current_user.id
    @comment.book_id = @book.id
    @comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find(params[:id]).destroy
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comments.html.erb
<table>
  <% @book.book_comments.each do |book_comment| %>
  <tr>
    <td>
        <%= link_to user_path(book_comment.user.id) do %>
        <%= image_tag book_comment.user.get_profile_image(50,50) %><br>
        <%= book_comment.user.name %>
        <% end %>
    </td>
    <td><%= book_comment.comment %></td>

    <% if book_comment.user == current_user %>
      <td><%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_comment_#{book_comment.id}" %></td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/book_comments/_form.html.erb
<%= form_with model: [book, comment], local: false do |f| %>
  <%= f.text_area :comment, rows: "5", cols: "85%", placeholder: "コメントはここに" %>
  <%= f.submit '送信' %>
<% end %>

app/views/book_comments/_index.html.erb
<table>
  <% book.book_comments.each do |book_comment| %>
  <tr>
    <td>
        <%= link_to user_path(book_comment.user.id) do %>
        <%= image_tag book_comment.user.get_profile_image(50,50) %><br>
        <%= book_comment.user.name %>
        <% end %>
    </td>
    <td><%= book_comment.comment %></td>

    <% if book_comment.user == current_user %>
      <td><%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_comment_#{book_comment.id}" %></td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/book_comments/create.js.erb
$('.comment_list').html("<%= j(render 'book_comments/index', book: @book) %>");
$('.comment_error').html("<%= j(render 'layouts/errors', obj: @comment) %>");
$('#book_comment_comment').val("");

app/views/book_comments/destroy.js.erb
$('.comment_list').html("<%= j(render 'book_comments/index', book: @book) %>");