config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about"
  get 'search' => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower'
    get 'followers' => 'relationships#followed'
  end

  resources :chats, only: [:show, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags

  has_many :favorited_users, through: :favorites, source: :user
  has_many :view_counts, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  is_impressionable counter_cache: true


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


  def self.search_for(search, word)
    if search == "perfect"
      @book = Book.where("title LIKE?", "#{word}" )
    elsif search == "forward"
      @book = Book.where("title LIKE?", "#{word}%" )
    elsif search == "backward"
      @book = Book.where("title LIKE?", "%#{word}" )
    else
      @book = Book.where("title LIKE?", "%#{word}%" )
    end
  end

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    new_tags.each do |new|
      new_book_tag = Tag.find_or_create_by(name: new)
      self.tags << new_book_tag
   end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @books = Book.all.order(params[:sort])
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorited_users).sort {|a,b|
      b.favorites.where(created_at: from...to).size <=>
      a.favorites.where(created_at: from...to).size
    }
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    tag_list = params[:book][:tag_name].split(",")
    if @book.save
      @book.save_tag(tag_list)
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render "index"
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    unless @user == current_user
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autocomplete: 'off', class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :tag_name, class: 'form-control book_tags' %>
  </div>

  <% if book.id == nil %>
  <div class="form-group" id="star">
    <%= f.label :rate %>
    <%= f.hidden_field :rate, id: :review_star %>
  </div>
    <script>
      $('#star').empty();
      $('#star').raty({
        size     : 20,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'book[rate]',
        half: true,
      });
    </script>
  <% else %>
    <%= render "books/static_rate", book: book %>
  <% end %>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user_id) do %>
          <%= image_tag book.user.get_profile_image(50,50) %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(book.id), class: "book_#{book.id}" do %>
            <%= book.title %>
          <% end %>
        </td>
        <td><%= book.body %></td>
        <td>
          <% book.tags.each do |tag| %>
            <li style="list-style: none;"><%= link_to tag.name, search_path(:range => 'tag', :word => tag.name ) %></li>
          <% end %>
          </td>
        <td id="favorites_btn_<%= book.id %>">
          <%= render 'favorites/btn', book: book %>
        </td>
        <td>コメント数：<%= book.book_comments.count %></td>
        <td id="star-rate<%= book.id %>"></td>
          <script>
            $('#star-rate<%= book.id %>').empty();
            $('#star-rate<%= book.id%>').raty({
              size: 20,
              starOff: '<%= asset_path('star-off.png') %>',
              starOn: '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= book.rate %>,
            });
          </script>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_static_rate.html.erb
<div id="star-rate<%= book.id %>" class="form-group"></div>
<script>
  $('#star-rate<%= book.id %>').empty();
  $('#star-rate<%= book.id %>').raty({
    size: 20,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= book.rate %>,
  });
});
</script>


<td id="star-rate<%= book.id %>"></td>
  <script>
    $('#star-rate<%= book.id %>').empty();
    $('#star-rate<%= book.id%>').raty({
      size: 20,
      starOff: '<%= asset_path('star-off.png') %>',
      starOn: '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      half: true,
      readOnly: true,
      score: <%= book.rate %>,
    });
  </script>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
  		<%= render 'layouts/errors', obj: @book %>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to "新しい順", books_path(sort: 'created_at DESC') %> |
      <%= link_to "評価の高い順", books_path(sort: 'rate DESC') %>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class='table'>
        <tr>
          <td>
            <%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image(100,100) %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td>
            <% @book.tags.each do |tag| %>
              <li style="list-style: none;"><%= link_to tag.name, search_path( :range => 'tag', :word => tag.name ) %></li>
            <% end %>
          </td>
          <td id="favorites_btn_<%= @book.id %>">
            <%= render 'favorites/btn', book: @book %>
          </td>
          <td>コメント数：<%= @book.book_comments.count %></td>
          <td id="star-rate<%= @book.id %>"></td>
            <script>
              $('#star-rate<%= @book.id %>').empty();
              $('#star-rate<%= @book.id%>').raty({
                size: 36,
                starOff: '<%= asset_path('star-off.png') %>',
                starOn: '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= @book.rate %>,
              });
            </script>

          <% if @user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      <div class="comment_list">
        <%= render 'book_comments/index', book: @book %>
      </div>
      <div class="comment_error">
        <%= render 'layouts/errors', obj: @comment %>
      </div>
      <%= render 'book_comments/form', book: @book, comment: @comment %>
    </div>
  </div>
</div>